/**
 * CA-1 — The six schemas exist and are the single source of the type.
 *
 * For every entity: (a) the fixture parses, and (b) for EVERY required key of
 * the fixture, a copy without that key is rejected. Case (b) is generated by
 * walking the fixture's own keys, so adding a required field without adding a
 * case is impossible.
 */
import { describe, expect, test } from 'vitest';
import type { ZodType } from 'zod';
import {
  CompetitionSchema,
  DecisionSchema,
  MatchSchema,
  ObservationSchema,
  TeamAliasSchema,
  TeamSchema,
} from '@/model';
import {
  competitionFixture,
  decisionFixture,
  matchFixture,
  observationFixture,
  teamAliasFixture,
  teamFixture,
} from '../fixtures/model';

const entities: ReadonlyArray<{
  readonly name: string;
  readonly schema: ZodType;
  readonly fixture: Record<string, unknown>;
}> = [
  { name: 'Competition', schema: CompetitionSchema, fixture: competitionFixture },
  { name: 'Team', schema: TeamSchema, fixture: teamFixture },
  { name: 'TeamAlias', schema: TeamAliasSchema, fixture: teamAliasFixture },
  { name: 'Match', schema: MatchSchema, fixture: matchFixture },
  { name: 'Observation', schema: ObservationSchema, fixture: observationFixture },
  { name: 'Decision', schema: DecisionSchema, fixture: decisionFixture },
];

describe.each(entities)('$name', ({ name, schema, fixture }) => {
  test('accepts the valid fixture', () => {
    expect(schema.parse(fixture)).toEqual(fixture);
  });

  const keys = Object.keys(fixture);

  test('the fixture is not empty (the generated table below would be vacuous)', () => {
    expect(keys.length).toBeGreaterThan(0);
  });

  test.each(keys)(`rejects a ${name} without "%s"`, (key) => {
    const withoutKey = { ...fixture };
    delete withoutKey[key];
    expect(schema.safeParse(withoutKey).success).toBe(false);
  });
});
