/**
 * Our own robots.txt (SPEC-004 CA-11).
 *
 * RN-11 read in reverse. We ask third parties to respect theirs — the letter
 * to the RFGF asks for exactly two lines of it — so having ours properly set
 * is not cosmetic. It is generated by the application rather than dropped in
 * `public/` so it cannot drift away from the routes it talks about.
 *
 * Nothing is disallowed: every route of this site exists to be read, and one
 * of them is the crawler page that third parties reach from our User-Agent.
 *
 * The courtesy comment carries the mailbox, and it is INTERPOLATED from
 * `contact.ts` (CA-13). A robots.txt is exactly the kind of place where an
 * address stays behind when the rest of the project migrates.
 */
import { MAILBOX } from '@/site/contact';

export function buildRobotsTxt(): string {
  return [
    `# marcador.gal — ${MAILBOX}`,
    '',
    'User-agent: *',
    'Allow: /',
    '',
  ].join('\n');
}
